### PR TITLE
Physics extension documentation

### PR DESCRIPTION
**Pull request by stevenvergenz**
I've started writing up what we have, as well as what we probably should have. If we can agree with the overview concepts, we can start working on schemata.

### CODE REVIEW

**Comment by Moguri** [comment]
Thanks for getting a start on this. My main issue with what you have so far is that this isn't what we actually export. For example, we do not export height and radius as these can be inferred from the dimensions (see [https://github.com/Moguri/BlenderPanda/blob/master/converter.py#L95](BlenderPanda) as an example). We also do not export convex or layers properties. Convex does not seem useful to me since we have a CONVEX_HULL shape type. We export dynamic, but @Kupoman and I agreed that static works out better. And, lastly, we don't export glTF 2.0 at the moment.

**Comment by stevenvergenz** [comment]
That's true, what I've written does not match what we export, nor the version of glTF we export. ~~However, I believe that everything I've written is necessary for third-party engines like Unity to create a proper rigid body component. glTF strives to be as render-ready as possible, and requiring additional processing by consumers to implement this extension goes against that.~~ Plus, Khronos has that contract out to update us to 2.0, so I'm confident that future-proofing this extension will prove useful. However, it would be simple enough to produce two versions of the extension for both versions of glTF. The only version-dependent field I've written is the "mesh" property.

EDIT: Upon a second reading of your comment, I think I understand what you're saying about the various size properties. If we only provide `dimensions`, consumers can infer radius/height/etc. from that, just as Blender does. I feared they'd have to crawl the vertex data for it.

**Comment by Moguri** [comment]
I've updated the docs based on what you started as c2e278b2104cabf1fe54d2478f7b74f6523fa738. Let me know what you think. I also included examples of getting shape information from `dimensions`.

**Comment by stevenvergenz** [comment]
Looks really good! We keep committing right past each other :)

1. Don't forget that glTF convention is Y-Up not Z-Up. That should probably be reflected in this extension.
2. Should the extension attempt a best fit primitive on the bounding box? I know you went with the Blender algorithm for prim matching, but for capsules and cylinders I feel like the longest axis should be the orientation axis, not the arbitrary up axis. What do you think?
3. Do you think my layers concept is useful? Many physics engines have something similar, it could be useful to allow collider groupings.
4. Your version left off the scene physics settings. Was that deliberate?

**Comment by stevenvergenz** [comment]
5. The CONE collider requires a direction to point in addition to long axis and radius.

**Comment by Moguri** [comment]
I wrote up the spec to match what we have now. We should open issues for layers, figuring out a good way to define shapes/dimensions, and scene settings (e.g., gravity).

Layers are very useful, but my current hang up is that I'd like to expose something like Bullet's groups and masks, which Blender supports for its game engine, but not in the general rigid body settings. So I need to figure out a good way to gather the data from Blender. Also, I don't know if all engines would support a more fine-grained group/mask approach, but those engines that do can also do layers (just match up groups and masks).

**Comment by Moguri** [comment]
I have opened issues #68, #69, and #70 to track the issues brought up in this PR about the current state of BLENDER_physics.

**Comment by stevenvergenz** [comment]
Since you have your own similar version, I'll go ahead and close out this PR. We'll discuss improvements in the various issues.

**Pull request closed without merging**
