### PR TITLE
Convert embedded images to a proper data-uri format

### PR DESCRIPTION
**Pull request by emackey**
When `Embed Image Data` is selected, the embedded image data can't be raw pixels.  It needs to be a proper data-URI format with an image MIME-type of [one of four known types](https://github.com/KhronosGroup/glTF/tree/master/specification#imageuri-white_check_mark).

This pull request converts embedded image data to PNG format.  It is based on code from [StackOverflow](http://stackoverflow.com/questions/902761/saving-a-numpy-array-as-an-image/19174800#19174800) and [BlenderSE](http://blender.stackexchange.com/questions/62072/does-blender-have-a-method-to-a-get-png-formatted-bytearray-for-an-image-via-pyt/62218#62218).

### CODE REVIEW

**Comment by Moguri** [comment]
The patch overall looks good to me, but I cannot vouch for the correctness of the PNG encoding. What kind of testing have you done on the changes?

**Comment by emackey** [comment]
I've run about 5 different images of varying sizes and depths through the conversion, and Google Chrome is able to correctly parse the resulting data-URI in each of those cases.  You can paste data-URIs into the address bar to directly to see an image that has been through this process.

If you want stronger testing, you could look for some sort of PNG validation.  A casual Google search reveals at least one [PNG Validator](http://www.libpng.org/pub/png/apps/pngcheck.html) out there, maybe someone with a Linux/*nix box could test it out.

**Comment by emackey** [comment]
There's also [a solution that uses Python Image Library](http://stackoverflow.com/questions/2408027/png-file-validation/2408049#2408049).

**Comment by emackey** [comment]
So it turns out that the PNG code here came from Blender source originally:

https://developer.blender.org/diffusion/B/browse/master/release/bin/blender-thumbnailer.py$155

(search for `png_pack` in the above).

**Comment by Moguri** [comment]
Testing with Chrome is fine enough (as long as something can load the data). Thanks for the patch!

**Pull request merged**
