### PR TITLE
Minor improvements/speedups

### PR DESCRIPTION
**Pull request by ideasman42**

### CODE REVIEW

**Comment by ideasman42** [comment]
Note, I didn't change logic here, but the `__eq__` function is merging data which is really bad (equality should only ever test, not manipulate data).
Suggest to make a method (`a.merge(b)` for example).

**Comment by Kupoman** [comment]
The data manipulation is a hack for getting some extra functionality out of dictionaries. I'll see if I can find a better way since you are right and it should not being doing that.

**Comment by ideasman42** [comment]
Ok. so this is being used for a 'remove-doubles' on export, from what I can tell...
think this is a bit risky users might want to keep verts touching but not be merged (especially if parts of the mesh are animated), a quick fix would be to include the index in the comparison.

Also note that this this isn't going to be reliable, since vector equality in mathutils allows for some very small differences _(it could be argued that it shouldn't, this decision was made a long time ago)_.
So its not ensured 2 vectors that equal will get the same hash.

**Comment by Kupoman** [comment]
Thanks for the changes Campbell! I'll add the sorting and check_circular options to the addon repo and the pseudo-addon code in this repo.

**Pull request merged**
