### PR TITLE
Move classes to own files

### PR DESCRIPTION
**Pull request by stevenvergenz**
In an effort to reduce the brobdingnagian size of blendergltf.py, this PR moves the handful of self-contained classes into their own files. This accounts for about 600 LOC.

### CODE REVIEW

**Comment by Moguri** [comment]
The new files do not follow PEP8 (imports on their own lines, spaces over tabs). I would also prefer to keep Accessor as a nested class of Buffer. Also, the "Fix mime type" commit is not related to this PR.

**Comment by stevenvergenz** [comment]
I've updated the style as you've requested, and changed the mime type back (that's better for a different PR, you're right). Could you explain your nested class preference though? Nested classes always seemed ugly to me, unless they were under some size threshold. Accessor is 100 lines though, 2/3 the size of the Buffer class itself. Since they *can* stand on their own, I think they *should*.

**Comment by Moguri** [comment]
I see Accessor as part of Buffer and not a stand-alone class. However, I would be okay with putting them in the same file and not nesting them. This way you only have to look at the one file to get all the details about how blendergltf handles buffers.

**Comment by Moguri** [comment]
Since there has not been activity on this PR in a while, and the PR no longer applies cleanly to master, I am closing this PR. However, we will make use of some of these ideas if/when we finally split up blendergltf.py. Thank you for your work on this!

**Pull request closed without merging**
